spring.application.name=AuthService

server.port=8080

# ===============================
# Google OAuth2
# ===============================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,email,profile

# ===============================
# JWT
# NOTE: this secret MUST be identical to the one in quantity-service,
# since quantity-service validates the tokens this service issues.
# ===============================

jwt.secret=MySuperSecretKeyForQuantityMeasurementApplication2026
spring.config.import=optional:classpath:application-local.properties
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
jwt.expiration=86400000
spring.profiles.active=local
